/* eslint quotes: 0 quote-props: 0 */

const baSemester1 = [
  {
    "title": "English Compulsory-I",
    "code": "BENG-101 (C)",
    "type": "compulsory",
    "branch": "b.a",
    "semester": 1,
  },
  {
    "title": "Introducing English Literature-I",
    "code": "BENG-101 (E)",
    "type": "elective",
    "branch": "b.a",
    "semester": 1,
  },
  {
    "title": "Economic Theory",
    "code": "BECO-101",
    "type": "regular",
    "branch": "b.a",
    "semester": 1,
  },
  {
    "title": "Elements Of Education",
    "code": "BEDU-101",
    "type": "regular",
    "branch": "b.a",
    "semester": 1,
  },
  {
    "title": "Physical Basis Of Geography",
    "code": "BGEO-101 (T)",
    "type": "regular",
    "branch": "b.a",
    "semester": 1,
  },
  {
    "title": "History Of Ancient India (Upto 1200 C)",
    "code": "BHIS-101",
    "type": "regular",
    "branch": "b.a",
    "semester": 1,
  },
  {
    "title": "Shamania Hindi-I",
    "code": "BHIN-101",
    "type": "regular",
    "branch": "b.a",
    "semester": 1,
  },
  {
    "title": "Political Theory-I",
    "code": "BPOL-101",
    "type": "regular",
    "branch": "b.a",
    "semester": 1,
  },
];

const baSemester2 = [
  {
    "title": "English Compulsory-II",
    "code": "BENG-202 (C)",
    "type": "compulsory",
    "branch": "b.a",
    "semester": 2,
  },
  {
    "title": "Introducing English Literature-II",
    "code": "BENG-202 (E)",
    "type": "elective",
    "branch": "b.a",
    "semester": 2,
  },
  {
    "title": "Money, Banking And International Trade",
    "code": "BECO-202",
    "type": "regular",
    "branch": "b.a",
    "semester": 2,
  },
  {
    "title": "Indian Education And Its Problems",
    "code": "BEDU-202",
    "type": "regular",
    "branch": "b.a",
    "semester": 2,
  },
  {
    "title": "Human Geography",
    "code": "BGEO-202 (T)",
    "type": "regular",
    "branch": "b.a",
    "semester": 2,
  },
];

const baSemester3 = [
  {
    "title": "Env. Science Compulsory",
    "code": "BEVS-303 (C)",
    "type": "compulsory",
    "branch": "b.a",
    "semester": 3,
  },
  {
    "title": "Reading Poetry And Drama",
    "code": "BENG-303 (E)",
    "type": "elective",
    "branch": "b.a",
    "semester": 3,
  },
  {
    "title": "Public Finance And Statistices",
    "code": "BECO-303",
    "type": "regular",
    "branch": "b.a",
    "semester": 3,
  },
  {
    "title": "Foundation Of Education",
    "code": "BEDU-303",
    "type": "regular",
    "branch": "b.a",
    "semester": 3,
  },
  {
    "title": "Geography Of Resources And Economic Activities",
    "code": "BGEO-303 (T)",
    "type": "regular",
    "branch": "b.a",
    "semester": 3,
  },
];


const baSemester4 = [
  {
    "title": "Skill Based Course Compulsory",
    "code": "BEVS-404 (C)",
    "type": "compulsory",
    "branch": "b.a",
    "semester": 4,
  },
  {
    "title": "Skill Based Course In English",
    "code": "BENG-404 (SBC)",
    "type": "elective",
    "branch": "b.a",
    "semester": 4,
  },
  {
    "title": "Indian Economy And Economy Of Arunachal Pradesh",
    "code": "BECO-404",
    "type": "regular",
    "branch": "b.a",
    "semester": 4,
  },
  {
    "title": "Teaching-Learning Process",
    "code": "BEDU-404",
    "type": "regular",
    "branch": "b.a",
    "semester": 4,
  },
  {
    "title": "Geography Of India",
    "code": "BGEO-404 (T)",
    "type": "regular",
    "branch": "b.a",
    "semester": 4,
  },
];

const baSemester5 = [
  {
    "title": "History of English Literature",
    "code": "BENG-505 (M)",
    "type": "elective",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "History of English Literature",
    "code": "BENG-505 (M)",
    "type": "elective",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "English Poetry From The Elizabethan To The Augustan Age",
    "code": "BENG-506 (M)",
    "type": "elective",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Reading Drama",
    "code": "BENG-507 (M)",
    "type": "elective",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Reading Fiction And Non-Fiction",
    "code": "BENG-508 (M)",
    "type": "elective",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Micro Economic Theory",
    "code": "BECO-505",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Macro Economic Theory",
    "code": "BECO-506",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "International Economics",
    "code": "BECO-507",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Basic Mathematics And Statistics",
    "code": "BECO-508",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Educational Psychology",
    "code": "BEDU-501",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Educational Technology",
    "code": "BEDU-502",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Population Education",
    "code": "BEDU-521",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Human Rights, Values And Peace Education",
    "code": "BEDU-522",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Guidance And Counselling In Education",
    "code": "BEDU-523",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Environmental Education",
    "code": "BEDU-524",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Geomorphology",
    "code": "BGEO-505 (M-1)-C",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "General Cartography Of India",
    "code": "BGEO-506 (M-2)-C",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Environmental Geography",
    "code": "BGEO-507 (M-3)-O",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Population Geography",
    "code": "BGEO-508 (M-4)-O",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Settlement Geography",
    "code": "BGEO-509 (M-5)-O",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
  {
    "title": "Agricultural Geography",
    "code": "BGEO-510 (M-6)-O",
    "type": "regular",
    "branch": "b.a",
    "semester": 5,
  },
];

const baSemester6 = [
  {
    "title": "Indian Writing In English",
    "code": "BENG-611 (M) A",
    "type": "elective",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Literature From Indian Languages In Translation",
    "code": "BENG-611 (M) B",
    "type": "elective",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "American Literature",
    "code": "BENG-612 (M) A",
    "type": "elective",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Linguistics",
    "code": "BENG-612 (M) B",
    "type": "elective",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Monetary Economics And Financial Institutions",
    "code": "BECO-609",
    "type": "regular",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Development Economics",
    "code": "BECO-610",
    "type": "regular",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "History Of Economic Thought",
    "code": "BECO-611",
    "type": "regular",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Issues Of Indian Economy",
    "code": "BECO-612",
    "type": "regular",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Curriculum Development",
    "code": "BECO-601",
    "type": "regular",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Education Measurement And Evaluation",
    "code": "BECO-602",
    "type": "regular",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Adult And Continuing Education",
    "code": "BECO-621",
    "type": "regular",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Education Administration And Planning",
    "code": "BECO-622",
    "type": "regular",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Teacher Education",
    "code": "BECO-623",
    "type": "regular",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Special Education",
    "code": "BECO-624",
    "type": "regular",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Climatology And Biogeography",
    "code": "BGEO-611 (M-7)-C",
    "type": "regular",
    "branch": "b.a",
    "semester": 6,
  },
  {
    "title": "Geographical Techniques And Project Work",
    "code": "BGEO-612 (M-8)-C",
    "type": "regular",
    "branch": "b.a",
    "semester": 6,
  },
];

const bcomSemester1 = [
  {
    "title": "Communicative English",
    "code": "BENG-101",
    "type": "regular",
    "branch": "b.com",
    "semester": 1,
  },
  {
    "title": "Business Economics",
    "code": "BCM-102",
    "type": "regular",
    "branch": "b.com",
    "semester": 1,
  },
  {
    "title": "Business Organisation",
    "code": "BCM-103",
    "type": "regular",
    "branch": "b.com",
    "semester": 1,
  },
  {
    "title": "Financial Accounting-I",
    "code": "BCM-104",
    "type": "regular",
    "branch": "b.com",
    "semester": 1,
  },
  {
    "title": "Environment Studies (Non-Credit Paper)",
    "code": "BCM-105",
    "type": "regular",
    "branch": "b.com",
    "semester": 1,
  },
];

const bcomSemester2 = [
  {
    "title": "Mathematics And Statistics",
    "code": "BCM-201",
    "type": "regular",
    "branch": "b.com",
    "semester": 2,
  },
  {
    "title": "Business Law And Regulatory Framework",
    "code": "BCM-202",
    "type": "regular",
    "branch": "b.com",
    "semester": 2,
  },
  {
    "title": "Financial Accounting - II",
    "code": "BCM-203",
    "type": "regular",
    "branch": "b.com",
    "semester": 2,
  },
  {
    "title": "Principles Of Management",
    "code": "BCM-204",
    "type": "regular",
    "branch": "b.com",
    "semester": 2,
  },
];

const bcomSemester3 = [
  {
    "title": "Income Tax",
    "code": "BCM-301",
    "type": "regular",
    "branch": "b.com",
    "semester": 3,
  },
  {
    "title": "Indian Financial System",
    "code": "BCM-302",
    "type": "regular",
    "branch": "b.com",
    "semester": 3,
  },
  {
    "title": "Company Law",
    "code": "BCM-303",
    "type": "regular",
    "branch": "b.com",
    "semester": 3,
  },
  {
    "title": "Corporate Accounting",
    "code": "BCM-304",
    "type": "regular",
    "branch": "b.com",
    "semester": 3,
  },
];

const bcomSemester4 = [
  {
    "title": "Marketing Management",
    "code": "BCM-401",
    "type": "regular",
    "branch": "b.com",
    "semester": 4,
  },
  {
    "title": "Human Resource Management",
    "code": "BCM-402",
    "type": "regular",
    "branch": "b.com",
    "semester": 4,
  },
  {
    "title": "Financial Management",
    "code": "BCM-403",
    "type": "regular",
    "branch": "b.com",
    "semester": 4,
  },
  {
    "title": "Entrepreneurship Development",
    "code": "BCM-404",
    "type": "regular",
    "branch": "b.com",
    "semester": 4,
  },
];

const bcomSemester5 = [
  {
    "title": "Computerised Accounting (Skill Based Paper)",
    "code": "BCM-501",
    "type": "regular",
    "branch": "b.com",
    "semester": 5,
  },
  {
    "title": "Advanced Financial Management*",
    "code": "BCM-502",
    "type": "regular",
    "branch": "b.com",
    "semester": 5,
  },
  {
    "title": "Cost Accounting*",
    "code": "BCM-503",
    "type": "regular",
    "branch": "b.com",
    "semester": 5,
  },
  {
    "title": "Advanced Accounting*",
    "code": "BCM-504",
    "type": "regular",
    "branch": "b.com",
    "semester": 5,
  },
];

const bcomSemester6 = [
  {
    "title": "Auditing (Skill Based Paper)",
    "code": "BCM-601",
    "type": "regular",
    "branch": "b.com",
    "semester": 6,
  },
  {
    "title": "Management Accounting*",
    "code": "BCM-602",
    "type": "regular",
    "branch": "b.com",
    "semester": 6,
  },
  {
    "title": "Investment Analysis And Portfolio Management*",
    "code": "BCM-603",
    "type": "regular",
    "branch": "b.com",
    "semester": 6,
  },
  {
    "title": "Financial Analysis And Reporting*",
    "code": "BCM-603",
    "type": "regular",
    "branch": "b.com",
    "semester": 6,
  },
];

const bscSemester1 = [
  {
    "title": "Inorganic, Physical And Organic Chemistry - 01",
    "code": "CHEM-T1-101",
    "type": "regular",
    "branch": "b.sc",
    "semester": 1,
  },
  {
    "title": "Microbes and Cryptogams",
    "code": "BOT-111",
    "type": "regular",
    "branch": "b.sc",
    "semester": 1,
  },
  {
    "title": "Practical based on - Paper - BOT - 111",
    "code": "BOT-102",
    "type": "regular",
    "branch": "b.sc",
    "semester": 1,
  },
  {
    "title": "Invertebrate Biosystematics and type specimen studies",
    "code": "BOT-102",
    "type": "regular",
    "branch": "b.sc",
    "semester": 1,
  },
];

const bscSemester2 = [
  {
    "title": "Inorganic, Physical And Organic Chemistry - 02",
    "code": "CHEM-T1-102",
    "type": "regular",
    "branch": "b.sc",
    "semester": 2,
  },
  {
    "title": "Inorganic, Physical And Laboratory Course - I",
    "code": "CHEM-P1-202",
    "type": "regular",
    "branch": "b.sc",
    "semester": 2,
  },
  {
    "title": "Phanerogams And Palaeobotany",
    "code": "BPT-121",
    "type": "regular",
    "branch": "b.sc",
    "semester": 2,
  },
  {
    "title": "Practical based on - Paper - BOT - 121",
    "code": "BOT-122",
    "type": "regular",
    "branch": "b.sc",
    "semester": 2,
  },
  {
    "title": "Vertebrate Biosystematics, Comparative Anatomy And Evolution",
    "code": "ZOO-T2-202",
    "type": "regular",
    "branch": "b.sc",
    "semester": 2,
  },
  {
    "title": "Identification, Dissection And Slide Preparation Of Vertebrate And Invertebrate Specimens (Practical)",
    "code": "ZOO-P2-202",
    "type": "regular",
    "branch": "b.sc",
    "semester": 2,
  },
  {
    "title": "Environmental Science (No Practical)",
    "code": "EVS-1202",
    "type": "regular",
    "branch": "b.sc",
    "semester": 2,
  },
];

const bscSemester3 = [
  {
    "title": "Water Treatment and Analysis - I",
    "code": "SBSC",
    "type": "regular",
    "branch": "b.sc",
    "semester": 3,
  },
  {
    "title": "Inorganic, Physical And Organic Chemistry-3",
    "code": "CHEM-T2303",
    "type": "regular",
    "branch": "b.sc",
    "semester": 3,
  },
  {
    "title": "Organic Chemistry Laboratory Course -II",
    "code": "CHEM-P2303",
    "type": "regular",
    "branch": "b.sc",
    "semester": 3,
  },
  {
    "title": "Microbiology And Plant Pathology",
    "code": "BOT-341",
    "type": "regular",
    "branch": "b.sc",
    "semester": 3,
  },
  {
    "title": "Practical",
    "code": "BOT-232",
    "type": "regular",
    "branch": "b.sc",
    "semester": 3,
  },
  {
    "title": "Cell Biology, Biochemistry And Genetics",
    "code": "ZOO-T3-303",
    "type": "regular",
    "branch": "b.sc",
    "semester": 3,
  },
  {
    "title": "Practical",
    "code": "ZOO-P3-303",
    "type": "regular",
    "branch": "b.sc",
    "semester": 3,
  },
  {
    "title": "Skill Based Subject",
    "code": "SBST-2303",
    "type": "regular",
    "branch": "b.sc",
    "semester": 3,
  },
];

const bscSemester4 = [
  {
    "title": "Inorganic, Physical And Organic Chemistry-4",
    "code": "CHEM-T2404",
    "type": "regular",
    "branch": "b.sc",
    "semester": 4,
  },
  {
    "title": "Physical Chemistry Laboratory Course-III",
    "code": "CHEM-P2404",
    "type": "regular",
    "branch": "b.sc",
    "semester": 4,
  },
  {
    "title": "Plant Physiology",
    "code": "BOT-241",
    "type": "regular",
    "branch": "b.sc",
    "semester": 4,
  },
  {
    "title": "Practical",
    "code": "BOT-242",
    "type": "regular",
    "branch": "b.sc",
    "semester": 4,
  },
  {
    "title": "Physiology And Development Biology",
    "code": "ZOO-T4-404",
    "type": "regular",
    "branch": "b.sc",
    "semester": 4,
  },
  {
    "title": "Practical",
    "code": "ZOO-P4-404",
    "type": "regular",
    "branch": "b.sc",
    "semester": 4,
  },
  {
    "title": "Skill Based Subject",
    "code": "SBST-2404",
    "type": "regular",
    "branch": "b.sc",
    "semester": 4,
  },
];

const bscSemester5 = [
  {
    "title": "Inorganic, Physical And Organic Chemistry-5",
    "code": "CHEM-T3505",
    "type": "regular",
    "branch": "b.sc",
    "semester": 5,
  },
  {
    "title": "Inorganic, Physical And Organic Chemistry-6",
    "code": "CHEM-T3506",
    "type": "regular",
    "branch": "b.sc",
    "semester": 5,
  },
  {
    "title": "Inorganic, Physical And Organic Chemistry-7",
    "code": "CHEM-T3507",
    "type": "regular",
    "branch": "b.sc",
    "semester": 5,
  },
  {
    "title": "Comparative Study Of Cryptogams",
    "code": "BOT-351",
    "type": "regular",
    "branch": "b.sc",
    "semester": 5,
  },
  {
    "title": "Plant Systematics Economic Botany",
    "code": "BOT-352",
    "type": "regular",
    "branch": "b.sc",
    "semester": 5,
  },
  {
    "title": "Cell Biology, Genetics And Evolution",
    "code": "BOT-353",
    "type": "regular",
    "branch": "b.sc",
    "semester": 5,
  },
  {
    "title": "Practical",
    "code": "BOT-354",
    "type": "regular",
    "branch": "b.sc",
    "semester": 5,
  },
  {
    "title": "Ecology, Ethology And Biostatistics",
    "code": "ZOO-T5-505",
    "type": "regular",
    "branch": "b.sc",
    "semester": 5,
  },
  {
    "title": "History, Biochemistry And Biochemical Technique",
    "code": "ZOO-T5-506",
    "type": "regular",
    "branch": "b.sc",
    "semester": 5,
  },
  {
    "title": "Cytogenetics And Bioinformatics",
    "code": "ZOO-T5-507",
    "type": "regular",
    "branch": "b.sc",
    "semester": 5,
  },
  {
    "title": "Practical",
    "code": "ZOO-T5-508",
    "type": "regular",
    "branch": "b.sc",
    "semester": 5,
  },
];


const bscSemester6 = [
  {
    "title": "Inorganic, Physical And Organic Chemistry-8",
    "code": "CHEM-T3609",
    "type": "regular",
    "branch": "b.sc",
    "semester": 6,
  },
  {
    "title": "Inorganic, Physical And Organic Chemistry-9",
    "code": "CHEM-T3610",
    "type": "regular",
    "branch": "b.sc",
    "semester": 6,
  },
  {
    "title": "Inorganic, Physical And Organic Chemistry-10",
    "code": "CHEM-T3611",
    "type": "regular",
    "branch": "b.sc",
    "semester": 6,
  },
  {
    "title": "Environmental Biology And Biostatistics",
    "code": "BOT-361",
    "type": "regular",
    "branch": "b.sc",
    "semester": 6,
  },
  {
    "title": "Biochemistry And Biological Techniques",
    "code": "BOT-362",
    "type": "regular",
    "branch": "b.sc",
    "semester": 6,
  },
  {
    "title": "Molecular Biology, Plant Biotechnology And Bioinformatics",
    "code": "BOT-363",
    "type": "regular",
    "branch": "b.sc",
    "semester": 6,
  },
  {
    "title": "Practical",
    "code": "BOT-364",
    "type": "regular",
    "branch": "b.sc",
    "semester": 6,
  },
  {
    "title": "Endocrinology And Immunology",
    "code": "ZOO-T6-609",
    "type": "regular",
    "branch": "b.sc",
    "semester": 6,
  },
  {
    "title": "Biodiversity And Conservation Biology",
    "code": "ZOO-T6-610",
    "type": "regular",
    "branch": "b.sc",
    "semester": 6,
  },
  {
    "title": "Molecular Biology And Recombinant Technology",
    "code": "ZOO-T6-611",
    "type": "regular",
    "branch": "b.sc",
    "semester": 6,
  },
  {
    "title": "Practical",
    "code": "ZOO-T6-612",
    "type": "regular",
    "branch": "b.sc",
    "semester": 6,
  },
];

module.exports = {
  subjects: [
    ...bcomSemester1,
    ...bcomSemester2,
    ...bcomSemester3,
    ...bcomSemester4,
    ...bcomSemester5,
    ...bcomSemester6,
    ...baSemester1,
    ...baSemester2,
    ...baSemester3,
    ...baSemester4,
    ...baSemester5,
    ...baSemester6,
    ...bscSemester1,
    ...bscSemester2,
    ...bscSemester3,
    ...bscSemester4,
    ...bscSemester5,
    ...bscSemester6,
  ],
  branchSubjects: {
    "b.com": [
      bcomSemester1,
      bcomSemester2,
      bcomSemester3,
      bcomSemester4,
      bcomSemester5,
      bcomSemester6,
    ],
    "b.a": [
      baSemester1,
      baSemester2,
      baSemester3,
      baSemester4,
      baSemester5,
      baSemester6,
    ],
    "b.sc": [
      bscSemester1,
      bscSemester2,
      bscSemester3,
      bscSemester4,
      bscSemester5,
      bscSemester6,
    ],
  },
};
